title: Reverdecer
email: 
description: Permaculture VanDwelling
baseurl: ''
url: 'https://reverdecer.annalisagross.com'
twitter_username: annalisa144
github_username: annalisa144
markdown: kramdown
theme: minima
future: false
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      date: ""
      categories: ""
      layout: "post"

# Name of repository, for use with Staticman
repository: "annalisa144/reverdecer"

# Staticman comments (see staticman.yml for configuration).
staticman:
  branch: "master"

